### ISSUE TITLE
make new-post 이후 make gen 하면 에러발생

### ISSUE THREAD

**Issue by nanha** [rhiokim/haroopress#187]
# 
# = generate to static page

./bin/gen.js

node.js:229
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
SyntaxError: Unexpected token b
    at Object.parse (native)
    at tokenizer (/home/nanhadev/haroopress/lib/haroo.js:41:25)
    at loadArticle (/home/nanhadev/haroopress/lib/haroo.js:121:16)
    at /home/nanhadev/haroopress/lib/haroo.js:258:38
    at Array.forEach (native)
    at initialize (/home/nanhadev/haroopress/lib/haroo.js:255:22)
    at new Haroo (/home/nanhadev/haroopress/lib/haroo.js:332:5)
    at Object.<anonymous> (/home/nanhadev/haroopress/lib/haroo.js:380:18)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
make: **\* [gen] 오류 1

이런 에러가 발생함.

**Comment by rhiokim** [comment]
테스트를 devel 브랜치에서 부탁드릴께요. (master 브랜치가 stable 하지 않습니다. ㅠ.ㅠ)
1. git checkout devel
2. make init
3. make new-post
4. make gen
5. make preview 

스텝으로 진행하면 됩니다.

**Comment by nanha** [comment]
ㅋㅋ 오케이요

나의 iPhone에서 보냄
1. 6. 30. 오후 6:07 Rhio Kimreply@reply.github.com 작성:

**Comment by nanha** [comment]
global install 되는 모듈때문에
permission 관련 에러발생함.

sudo make init 할 필요성이 있네요.

2012/6/30 Rhio Kim <
reply@reply.github.com

> 테스트를 devel 브랜치에서 부탁드릴께요. (master 브랜치가 stable 하지 않습니다. ㅠ.ㅠ)
> 1. git checkout devel
> 2. make init
> 3. make new-post
> 4. make gen
> 5. make preview
> 
> 스텝으로 진행하면 됩니다.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rhiokim/haroopress/issues/187#issuecomment-6683957

## 

# ==================================================

# @author

# 박난하 PD (Pull Devel) / KTH / DevOps팀 / 개발실

#

# 156-712

# 서울시 동작구 신대방2동 395-62 삼성보라매옴니타워

#

# T) 02-3289-2565

# F) 02-3289-2007

# E) nanhapark@kthcorp.com

#
#

# @introduce

# Seoul, Korea FRENDS.KR 그룹에서 활동중

# :) Javascript(Node.JS), python, perl, bash, php

#

# @usage

# \- Node.js Q&A; 게시판: http://nodeqa.com

# \- Node.js Nodeman: http://nodeman.org

# \- Node.js Black Edition: http://black.nodeman.org

# \- 나꼼수여 영원하라: http://naggomsu.nanha.com

# ==================================================

**Comment by nanha** [comment]
엇. make init 프로세서에서

테마부분 잘 되던게

# = update & initialize git submodules

git submodule update --init --recursive
Cloning into source/themes...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:haroopress/haroopress-themes.git' into submodule
path 'source/themes' failed
make: **\* [update] Error 1

갑자기 에러나네.. 왠 git 퍼미션?

2012/6/30 Rhio Kim <
reply@reply.github.com

> 테스트를 devel 브랜치에서 부탁드릴께요. (master 브랜치가 stable 하지 않습니다. ㅠ.ㅠ)
> 1. git checkout devel
> 2. make init
> 3. make new-post
> 4. make gen
> 5. make preview
> 
> 스텝으로 진행하면 됩니다.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rhiokim/haroopress/issues/187#issuecomment-6683957

## 

# ==================================================

# @author

# 박난하 PD (Pull Devel) / KTH / DevOps팀 / 개발실

#

# 156-712

# 서울시 동작구 신대방2동 395-62 삼성보라매옴니타워

#

# T) 02-3289-2565

# F) 02-3289-2007

# E) nanhapark@kthcorp.com

#
#

# @introduce

# Seoul, Korea FRENDS.KR 그룹에서 활동중

# :) Javascript(Node.JS), python, perl, bash, php

#

# @usage

# \- Node.js Q&A; 게시판: http://nodeqa.com

# \- Node.js Nodeman: http://nodeman.org

# \- Node.js Black Edition: http://black.nodeman.org

# \- 나꼼수여 영원하라: http://naggomsu.nanha.com

# ==================================================

**Comment by rootband** [comment]
root쪽에 ssh 문제입니다. ssh public key를 root/.ssh/에 복사해주셔야 합니다.
