### ISSUE TITLE
make gh-pages 오류

### ISSUE THREAD

**Issue by rhiokim** [rhiokim/haroopress#227]
make 전반적으로 process 의 디렉토리가 윈도우 시스템과 잘 맞지 않음

_deploy 디렉토리는 생성하나
git init 는 제대로 되지 않음

**Comment by rhiokim** [comment]
우분투에서도 이 에러가 뜨네요.

haroo> Save? [y/n] : y

= clear public & deployment directories

./bin/clear.js
haroo> clear to deploy directory¶

haroo> clear to public directory

= setup repository for deployment

cd ./bin/;./gh-pages.js

node.js:201
throw e; // process.nextTick error, or 'error' event on first tick
^
TypeError: Object # has no method 'existsSync'
at Object. (/path/to/haroopress/bin/gh-pages.js:19:7)
at Module._compile (module.js:441:26)
at Object..js (module.js:459:10)
at Module.load (module.js:348:32)
at Function._load (module.js:308:12)
at Array.0 (module.js:479:10)
at EventEmitter._tickCallback (node.js:192:41)
make: **\* [gh-pages] 오류 1

@Jihoon-Kong 님이 올려주신 이슈인데 제가 잘못 클릭해서 커맨트를 삭제해버렸네요. 다시 올립니다.
