### ISSUE TITLE
make init 시 CXX(target) Release/obj.target/robotskirt/src/robotskirt.o 가 없어서 중단되는 현상

### ISSUE THREAD

**Issue by ghost** [rhiokim/haroopress#303]
하루프레스 클론 후 `make init` 해서 설치 진행시 중간에

CXX(target) Release/obj.target/robotskirt/src/robotskirt.o 가 없어서 애러가 납니다.

```
npm install -g robotskirt

혹은 

npm install robotskirt 

```

두 방법을 다 해보았는데..

마찬가지로 

CXX(target) Release/obj.target/robotskirt/src/robotskirt.o 가 없어서 에러가 납니다.

---

로그입니다.

```
$ npm install robotskirt
npm http GET https://registry.npmjs.org/robotskirt
npm http 304 https://registry.npmjs.org/robotskirt

> robotskirt@2.7.1 install /home/사용자/hp/node_modules/robotskirt
> node-gyp rebuild

make: Entering directory `/home/사용자/hp/node_modules/robotskirt/build'
  CC(target) Release/obj.target/sundown/src/autolink.o
  CC(target) Release/obj.target/sundown/src/buffer.o
  CC(target) Release/obj.target/sundown/src/houdini_href_e.o
  CC(target) Release/obj.target/sundown/src/houdini_html_e.o
  CC(target) Release/obj.target/sundown/src/houdini_html_u.o
  CC(target) Release/obj.target/sundown/src/houdini_js_e.o
  CC(target) Release/obj.target/sundown/src/houdini_js_u.o
  CC(target) Release/obj.target/sundown/src/houdini_uri_e.o
  CC(target) Release/obj.target/sundown/src/houdini_uri_u.o
  CC(target) Release/obj.target/sundown/src/houdini_xml_e.o
  CC(target) Release/obj.target/sundown/src/html.o
  CC(target) Release/obj.target/sundown/src/html_smartypants.o
  CC(target) Release/obj.target/sundown/src/markdown.o
  CC(target) Release/obj.target/sundown/src/stack.o
  AR(target) Release/obj.target/sundown.a
  COPY Release/sundown.a
  CXX(target) Release/obj.target/robotskirt/src/robotskirt.o
make: g++: 명령을 찾지 못했음
make: *** [Release/obj.target/robotskirt/src/robotskirt.o] 오류 127
make: Leaving directory `/home/b사용자/hp/node_modules/robotskirt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/사용자/.nvm/v0.8.10/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.8.0-25-generic
gyp ERR! command "node" "/home/사용자/.nvm/v0.8.10/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/사용자/hp/node_modules/robotskirt
gyp ERR! node -v v0.8.10
gyp ERR! node-gyp -v v0.10.3
gyp ERR! not ok 
npm ERR! robotskirt@2.7.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the robotskirt@2.7.1 install script.
npm ERR! This is most likely a problem with the robotskirt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls robotskirt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-25-generic
npm ERR! command "/home/사용자/.nvm/v0.8.10/bin/node" "/home/사용자/.nvm/v0.8.10/bin/npm" "install" "robotskirt"
npm ERR! cwd /home/사용자/hp
npm ERR! node -v v0.8.10
npm ERR! npm -v 1.1.62
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/사용자/hp/npm-debug.log
npm ERR! not ok code 0

$ 

```

**Comment by rhiokim** [comment]
g++ 명령어를 찾지 못하고 있네요.

ref. : http://ubuntuforums.org/showthread.php?t=1464768

**Comment by ghost** [comment]
앗.. 그러고보니 현재 설치하려는 곳에는 필요 라이브러리 설치 절차를 건너뛰었네요. ;;
제 부주의네요. ㅠㅠ
