### ISSUE TITLE
설치 중 'gyp: binding.gyp not found' 에러 발생했습니다.

### ISSUE THREAD

**Issue by ghost** [rhiokim/haroopress#305]
https://github.com/haroopress/haroopress-data/blob/master/articles/haroopress-install-requirements/index.markdown

글을 통해서 필요한 라이브러리 설치 후 `make init` 했더니 에러가 납니다.

```
gyp: binding.gyp not found (cwd: /home/사용자/hp) while trying to load binding.gyp
```

이상하게도 ... 데탐에는 설치가 되는데 노트북에서는 에러가 나네요.

```
$ make init
npm install -g node-gyp
npm http GET https://registry.npmjs.org/node-gyp
npm http 304 https://registry.npmjs.org/node-gyp
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/npmlog
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/osenv
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/npmlog
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/osenv
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/ansi
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/cookie-jar
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/form-data/0.0.8
npm http 304 https://registry.npmjs.org/ansi
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/block-stream
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/aws-sign
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/form-data/0.0.8
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
/home/사용자/.nvm/v0.8.15/bin/node-gyp -> /home/사용자/.nvm/v0.8.15/lib/node_modules/node-gyp/bin/node-gyp.js
node-gyp@0.10.4 /home/사용자/.nvm/v0.8.15/lib/node_modules/node-gyp
├── osenv@0.0.3
├── graceful-fs@1.2.2
├── mkdirp@0.3.5
├── which@1.0.5
├── rimraf@2.2.0
├── semver@2.0.8
├── glob@3.2.1 (inherits@1.0.0)
├── npmlog@0.0.3 (ansi@0.1.2)
├── nopt@2.1.1 (abbrev@1.0.4)
├── minimatch@0.2.12 (sigmund@1.0.0, lru-cache@2.3.0)
├── fstream@0.1.22 (inherits@1.0.0)
├── tar@0.1.17 (inherits@1.0.0, block-stream@0.0.6)
└── request@2.21.0 (json-stringify-safe@4.0.0, forever-agent@0.5.0, aws-sign@0.3.0, qs@0.6.5, tunnel-agent@0.3.0, oauth-sign@0.3.0, cookie-jar@0.3.0, node-uuid@1.4.0, mime@1.2.9, http-signature@0.9.11, form-data@0.0.8, hawk@0.13.1)
git submodule update --init --recursive
cd ./node_modules/robotskirt;node-gyp rebuild
/bin/sh: 1: cd: can't cd to ./node_modules/robotskirt
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.4
gyp info using node@0.8.15 | linux | ia32
gyp info spawn python
gyp info spawn args [ '/home/사용자/.nvm/v0.8.15/lib/node_modules/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/사용자/hp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/사용자/.nvm/v0.8.15/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/사용자/.node-gyp/0.8.15/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/사용자/.node-gyp/0.8.15',
gyp info spawn args   '-Dmodule_root_dir=/home/사용자/hp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/사용자/hp) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/사용자/.nvm/v0.8.15/lib/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.8.0-25-generic
gyp ERR! command "node" "/home/사용자/.nvm/v0.8.15/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/사용자/hp
gyp ERR! node -v v0.8.15
gyp ERR! node-gyp -v v0.10.4
gyp ERR! not ok 
make: *** [initialize] 오류 1

```

**Comment by rhiokim** [comment]
에러 내용 중간에 보시면

```
cd ./node_modules/robotskirt;node-gyp rebuild
/bin/sh: 1: cd: can't cd to ./node_modules/robotskirt
```

이 부분이 있습니다.

`./node_modules/robotskirt` 가 존재하는 지 확인하시고 있는 경우 해당 위치에서 

`node-gyp rebuild` 해보시기 바랍니다.

문제 없이 컴파일이 된다면 사용하고 계시는 터미널 환경에서 아래의 문제를 먼저 해결해야할 것 같습니다.

```
/bin/sh: 1: cd: can't cd to ./node_modules/robotskirt
```

**Comment by ghost** [comment]
하루프레스설치 위치에서 

npm install robotskirt 후

make init 해주니 정상작동합니다. gcc 설치 후에 robotskirt를 안설치해줬네요. ^^;;
