### ISSUE TITLE
make update 이후 생기는 module error

### ISSUE THREAD

**Issue by insanehong** [rhiokim/haroopress#313]
make update 이후 node_module  들이 업데이트 되면서(npm update) 생기는 error 들

```
'========================================
    = clear public & deployment directories
    ========================================
    ./bin/clear.js
    haroo> clear to deploy directory¶
    haroo> clear to public directory
    ========================================
    = generate to static page
    ========================================
    ./bin/gen.js

    module.js:340
        throw err;
              ^
    Error: Cannot find module './build/Release/robotskirt'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:362:17)
        at require (module.js:378:17)
        at Object.<anonymous> (/.../node_modules/robotskirt/index.js:1:72)
        at Module._compile (module.js:449:26)
        at Object.Module._extensions..js (module.js:467:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:362:17)
    make: *** [gen] Error 1
```

과 

`
`findit.sync` method 를 찾을수 없다는 error 가 생김

`make gen` 명령어를 수행하면 발생

**Comment by rhiokim** [comment]
devel 체크아웃 받아서 테스트 함 해봐주세요.

**Comment by rhiokim** [comment]
해결되었습니다.
