### ISSUE TITLE
make init 설치 에러

### ISSUE THREAD

**Issue by hommeYo** [rhiokim/haroopress#320]
너무 모르는게 많아서;;
make init 에서 해결이 안되네요. 다른 비슷한 이슈들도 보고 따라하고는 있는데
아래와 같은 메시지가 뜨는데 robotskirt가 설치가 안돼서 그런가요?
haroopress node_modules 폴더 안에는 있는데
robotskirt를 global 설치해야 되는건가요? global설치도 에러가 나는데 이유를 잘 모르겠네요.

> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.
> make[1]: **\* [Release/obj.target/robotskirt/src/robotskirt.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Darwin 15.0.0
> gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
> gyp ERR! cwd /Users/hommeYo/hommeyo.github.com/node_modules/robotskirt
> gyp ERR! node -v v5.4.1
> gyp ERR! node-gyp -v v3.2.1
> gyp ERR! not ok 
> make: **\* [initialize] Error 1

**Comment by ZenRdot** [comment]
$ nvm install 0.10
하시고 다시 make init 해보세요.
